### ISSUE TITLE
Running Unity Scene does not pick up video being streamed from Jetson. 

### ISSUE THREAD

**Issue by jdagdelen** [augcog/IRG-RACING-VR#4]
I can see the video stream from the front RealSense camera by running the following on my PC,
```
gst-launch-1.0 udpsrc port=5001 ! application/x-rtp, encoding-name=H264,payload=96 ! rtph264depay ! h264parse ! avdec_h264 ! autovideosink
``` 
but when I run the SampleScene in Unity the video does not show up in the display of the cockpit. Since I can receive the stream with gstreamer, this means something in the Unity app is not working.

**Comment by jdagdelen** [comment]
The issue seems to be related to a DllNotFoundException when I try to run the project. The GStreamerReader.dll is not being recognized by Unity, even though it is in the project. Do I need to recompile this or something?

**Comment by jdagdelen** [comment]
I tried recompiling, but it's still not being recognized.

**Comment by iacChris** [comment]
I had the similar issue. I am trying to downgrade to Unity 2019.3.4 now and test again.

**Comment by jdagdelen** [comment]
It seems like opencv_world410.lib is a dependency of the GStreamerReceiver.dll, which means it was compiled for OpenCV 4.1.0

**Comment by jdagdelen** [comment]
Best route forward is to ditch the existing Unity project. I will update with working code that uses mRay gstreamer plugin.
