### ISSUE TITLE
roar-vr.py sometimes not sending realsense front camera data

### ISSUE THREAD

**Issue by jdagdelen** [augcog/IRG-RACING-VR#7]
I'm not sure what's causing this, but sometimes I only get the rear camera stream, and not the front. Seems like gstreamer feed isn't being sent for realsense?

**Comment by wuxiaohua1011** [comment]
I have not installed this package (heard it was a nightmare lol)

But if you look at this script
[https://github.com/augcog/ROAR_VR/blob/master/video/stream.py](https://github.com/augcog/ROAR_VR/blob/master/video/stream.py)

It seems like this is where gstreamer data originated from, maybe try uncommenting those cv2 linees will help debug

**Comment by wuxiaohua1011** [comment]
from looking at the code, im pretty sure that what they meant by the code is that:
[send()](https://github.com/augcog/ROAR_VR/blob/master/video/stream.py#L24) will send the video feed from CSI camera (which is the camera on the back of the car) to gstreamer pipeline

[sendrs()](https://github.com/augcog/ROAR_VR/blob/master/video/stream.py#L58), which probably stand for send_realse_sense, is INTENDED to send video feed from intel realsense to gstreamer pipeline.


I would check several things
1. what does the bitrate value mean, for CSI camera, bitrate=8000000, for realsense, bitrate=400000
2. is the receiver listening on 127.0.0.1:5001 for the front camera?

**Comment by jdagdelen** [comment]
Restarting Unity and the Jetson seems to fix it. Not sure why, but yeah...
